services:
  - type: static_site
    name: your-static-site
    env: static
    buildCommand: echo "Build completed"
    publishDirectory: .
    headers:
      - key: "Access-Control-Allow-Origin"
        value: "*"
      - key: "Access-Control-Allow-Methods"
        value: "GET, POST, OPTIONS"
      - key: "Access-Control-Allow-Headers"
        value: "Content-Type"
